#!/usr/bin/env bash
# Download finalizer script
FINALIZER_PATH="$PWD/flexipatch-finalizer.sh"
if [ ! -f "$FINALIZER_PATH" ]; then
	curl -H "Cache-Control: no-cache" -LO https://raw.githubusercontent.com/bakkeby/flexipatch-finalizer/master/flexipatch-finalizer.sh
	echo "Downloaded finalizer to $FINALIZER_PATH."
fi

# Run finalizer script
OUTPUT_DIR=$1
. "$FINALIZER_PATH" -r -d "$PWD" -o "$OUTPUT_DIR"
